services:
  postgres-replica:
    image: postgres:18
    container_name: postgres-replica
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      POSTGRES_USER: localadmin
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: replica_db
      PGPORT: 5433
    command: ["postgres", "-c", "port=5433"]
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata:
